#Likes

INSERT INTO LIKES (UID, ProjID) VALUES ('RyanYu', '86101');

INSERT INTO LIKES (UID, ProjID) VALUES ('RyanYu', '86103');

INSERT INTO LIKES (UID, ProjID) VALUES ('RyanYu', '86106');

INSERT INTO LIKES (UID, ProjID) VALUES ('RyanYu', '86107');

INSERT INTO LIKES (UID, ProjID) VALUES ('BarryZhao', '86101');

INSERT INTO LIKES (UID, ProjID) VALUES ('BarryZhao', '86106');

INSERT INTO LIKES (UID, ProjID) VALUES ('BarryZhao', '86103');

INSERT INTO LIKES (UID, ProjID) VALUES ('BarryZhao', '86104');

INSERT INTO LIKES (UID, ProjID) VALUES ('BobInBrooklyn', '86101');

INSERT INTO LIKES (UID, ProjID) VALUES ('BobInBrooklyn', '86102');

INSERT INTO LIKES (UID, ProjID) VALUES ('BobInBrooklyn', '86103');

INSERT INTO LIKES (UID, ProjID) VALUES ('BobInBrooklyn', '86104');

INSERT INTO LIKES (UID, ProjID) VALUES ('BobInBrooklyn', '86105');

INSERT INTO LIKES (UID, ProjID) VALUES ('Sofia250', '86102');

INSERT INTO LIKES (UID, ProjID) VALUES ('Sofia250', '86103');

INSERT INTO LIKES (UID, ProjID) VALUES ('Sofia250', '86104');

INSERT INTO LIKES (UID, ProjID) VALUES ('Sofia250', '86105');

INSERT INTO LIKES (UID, ProjID) VALUES ('DanStevens', '86101');

INSERT INTO LIKES (UID, ProjID) VALUES ('DanStevens', '86103');

INSERT INTO LIKES (UID, ProjID) VALUES ('DanStevens', '86107');

INSERT INTO LIKES (UID, ProjID) VALUES ('DanStevens', '86108');

INSERT INTO LIKES (UID, ProjID) VALUES ('LukeEvans', '86101');

INSERT INTO LIKES (UID, ProjID) VALUES ('LukeEvans', '86103');

INSERT INTO LIKES (UID, ProjID) VALUES ('LukeEvans', '86106');

INSERT INTO LIKES (UID, ProjID) VALUES ('CobieSmulders', '86101');

INSERT INTO LIKES (UID, ProjID) VALUES ('CobieSmulders', '86103');

INSERT INTO LIKES (UID, ProjID) VALUES ('CobieSmulders', '86108');

INSERT INTO LIKES (UID, ProjID) VALUES ('JenniferLawrence', '86101');

INSERT INTO LIKES (UID, ProjID) VALUES ('JenniferLawrence', '86102');

INSERT INTO LIKES (UID, ProjID) VALUES ('JenniferLawrence', '86103');

INSERT INTO LIKES (UID, ProjID) VALUES ('JenniferLawrence', '86104');

INSERT INTO LIKES (UID, ProjID) VALUES ('TaronEgerton', '86101');

INSERT INTO LIKES (UID, ProjID) VALUES ('TaronEgerton', '86103');

INSERT INTO LIKES (UID, ProjID) VALUES ('TaronEgerton', '86106');

INSERT INTO LIKES (UID, ProjID) VALUES ('TomCruise', '86103');

INSERT INTO LIKES (UID, ProjID) VALUES ('TomCruise', '86106');

INSERT INTO LIKES (UID, ProjID) VALUES ('WentworthMiller', '86101');

INSERT INTO LIKES (UID, ProjID) VALUES ('JamesMcAvoy', '86103');

INSERT INTO LIKES (UID, ProjID) VALUES ('JamesMcAvoy', '86104');

INSERT INTO LIKES (UID, ProjID) VALUES ('JamesMcAvoy', '86108');

INSERT INTO LIKES (UID, ProjID) VALUES ('AmyAdams', '86102');

